/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Meeting;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-29T16:53:00.885Z[GMT]")
@Api(value = "meetings", description = "the meetings API")
public interface MeetingsApi {

    @ApiOperation(value = "Add new meeting", nickname = "createMeeting", notes = "", tags={ "meetings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Bad request") })
    @RequestMapping(value = "/meetings",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> createMeeting(@ApiParam(value = "Meeting object that needs to be created" ,required=true )  @Valid @RequestBody Meeting body
);


    @ApiOperation(value = "Delete meeting", nickname = "deleteMeeting", notes = "", tags={ "meetings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Bad request"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Meeting not found") })
    @RequestMapping(value = "/meetings/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<String> deleteMeeting(@Min(1)@ApiParam(value = "Meeting id",required=true, allowableValues="") @PathVariable("id") Integer id
);


    @ApiOperation(value = "Update meeting", nickname = "editMeeting", notes = "", tags={ "meetings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Bad request"),
        @ApiResponse(code = 404, message = "Meeting not found") })
    @RequestMapping(value = "/meetings/{id}",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<String> editMeeting(@ApiParam(value = "Meeting object that needs to be created" ,required=true )  @Valid @RequestBody Meeting body
,@Min(1)@ApiParam(value = "Meeting id",required=true, allowableValues="") @PathVariable("id") Integer id
);


    @ApiOperation(value = "Get meeting by id", nickname = "getMeeting", notes = "", response = Meeting.class, tags={ "meetings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Meeting.class),
        @ApiResponse(code = 400, message = "Bad request"),
        @ApiResponse(code = 404, message = "Meeting not found") })
    @RequestMapping(value = "/meetings/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Meeting> getMeeting(@Min(1)@ApiParam(value = "Meeting id",required=true, allowableValues="") @PathVariable("id") Integer id
);


    @ApiOperation(value = "Get all meetings", nickname = "getMeetings", notes = "", tags={ "meetings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Bad request") })
    @RequestMapping(value = "/meetings",
        method = RequestMethod.GET)
    ResponseEntity<List<Meeting>> getMeetings();

}
